import { writeFileSync } from "node:fs";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/128.0";
const dec = (s) => s.replace(/&eacute;/g, "é").replace(/&egrave;/g, "è").replace(/&ecirc;/g, "ê")
  .replace(/&agrave;/g, "à").replace(/&ccedil;/g, "ç").replace(/&ocirc;/g, "ô").replace(/&icirc;/g, "î")
  .replace(/&#039;/g, "'").replace(/&amp;/g, "&");

const home = await (await fetch("https://maree.info/", { headers: { "User-Agent": UA } })).text();
const re = /<a href="\/(\d{1,4})" id="Port\d+_0"[^>]*>([^<]+)<\/a>/g;
const seen = new Set(), list = [];
let m;
while ((m = re.exec(home))) { if (!seen.has(m[1])) { seen.add(m[1]); list.push({ id: m[1], label: dec(m[2]) }); } }

const ports = [];
for (const p of list) {
  try {
    const html = await (await fetch(`https://maree.info/${p.id}`, { headers: { "User-Agent": UA } })).text();
    const la = html.match(/itemprop="latitude" content="([-\d.]+)"/);
    const lo = html.match(/itemprop="longitude" content="([-\d.]+)"/);
    if (la && lo) ports.push({ id: p.id, label: p.label, lat: Number(la[1]), lon: Number(lo[1]) });
  } catch { /* skip a port that fails; nearest-match still works */ }
}
writeFileSync(new URL("../web/js/data/ports.js", import.meta.url),
  "// maree.info ports (Channel + Atlantic coast). Generated by scripts/build-ports.mjs.\n" +
  "export const PORTS = " + JSON.stringify(ports) + ";\n");
console.log(`wrote ${ports.length} ports`);
